bike_evenement:
    resource: "@BikeBundle/Resources/config/routing/evenement.yml"
    prefix:   /evenement

# Front Office Routing
bike_homepage:
    path:     /
    defaults: { _controller: BikeBundle:Default:index }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Back Office Routing
bike_admin_homepage:
    path:     /
    defaults: { _controller: BikeBundle:Default:indexAdmin }
bike_reclamation:
    resource: "@BikeBundle/Resources/config/routing/reclamation.yml"
    prefix:   /reclamation