services:
#    bike.example:
#        class: BikeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  app.form.registration:
    class: BikeBundle\Form\UtilisateurType
    tags:
      - { name: form.type, alias: app_user_registration }